/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Generate a new random 128-bit ID as a 32-char lower-case hex string. */
export declare function newId(): string
export interface ExpectedStreamVersionInput {
  streamId: string
  version: number
}
export interface EventInput {
  /** 32-char hex; generated when omitted. */
  eventId?: string
  streamId: string
  eventType: string
  occurredAtMs: number
  payload?: Buffer
}
export interface ProjectionPutInput {
  key: Buffer
  value: Buffer
}
export interface ProjectionPatchInput {
  projection: string
  expectedVersion: number
  puts?: Array<ProjectionPutInput>
  deletes?: Array<Buffer>
}
export interface JobSpecInput {
  /** 32-char hex; generated when omitted. */
  jobId?: string
  queue: string
  partitionKey: string
  payload: Buffer
  /** "reconcilable" (default) or "idempotent" (requires `idempotencyKey`). */
  effectMode?: string
  idempotencyKey?: string
  notBeforeMs?: number
  maxAttempts?: number
}
export interface JobAckInput {
  jobId: string
  leaseToken: string
  resultDigest?: Buffer
}
export interface JobFailureInput {
  jobId: string
  leaseToken: string
  errorSummary?: string
  /** Delay before the job becomes claimable again; store default when omitted. */
  retryAfterMs?: number
}
export interface JobCancellationInput {
  jobId: string
  /** Required to cancel a leased job; omit for unleased jobs. */
  leaseToken?: string
}
export interface JobResolutionInput {
  jobId: string
  /** "retry", "markSucceeded", or "markDead". */
  resolution: string
}
export interface CommitBatchInput {
  /**
   * 32-char hex; generated when omitted. Supply one to be able to recover
   * an indeterminate commit with `recoverTransaction`.
   */
  transactionId?: string
  committedAtMs: number
  expectedStreamVersions?: Array<ExpectedStreamVersionInput>
  events?: Array<EventInput>
  projectionPatches?: Array<ProjectionPatchInput>
  enqueueJobs?: Array<JobSpecInput>
  ackJobs?: Array<JobAckInput>
  failJobs?: Array<JobFailureInput>
  cancelJobs?: Array<JobCancellationInput>
  resolveUncertainJobs?: Array<JobResolutionInput>
}
export interface CommitReceiptOutput {
  transactionId: string
  transactionSequence: number
  committedAtMs: number
}
export interface ClaimRequestInput {
  queue: string
  workerId: string
  nowMs: number
  leaseMs: number
  limit: number
}
export interface ClaimedJobOutput {
  jobId: string
  queue: string
  partitionKey: string
  payload: Buffer
  workerId: string
  leaseToken: string
  attempt: number
  leaseExpiresAtMs: number
  idempotencyKey?: string
}
/**
 * Outcome of `claimJobs` or `recoverClaim`.
 *
 * `kind` is "noop", "maintenanceCommitted", "committed", or (recovery only)
 * "absent". `staleJobs` lists job IDs that committed under the claim but must
 * not be executed with the recovered tokens.
 */
export interface ClaimOutcomeOutput {
  kind: string
  transactionId?: string
  jobs: Array<ClaimedJobOutput>
  staleJobs: Array<string>
}
export interface LeaseExtensionReceiptOutput {
  jobId: string
  attempt: number
  leaseExpiresAtMs: number
}
/**
 * Outcome of `recoverTransaction`: `kind` is "committed" (with the original
 * receipt fields) or "absent" (safe to resubmit the same batch).
 */
export interface TransactionRecoveryOutput {
  kind: string
  receipt?: CommitReceiptOutput
}
export interface JobInfoOutput {
  jobId: string
  queue: string
  partitionKey: string
  state: string
  attempt: number
  leaseExpiresAtMs?: number
  workerId?: string
  errorSummary?: string
}
/** One page from `jobsPage`; pass `nextAfterSequence` back to fetch the next page. */
export interface JobsPageOutput {
  jobs: Array<JobInfoOutput>
  nextAfterSequence: number
}
export interface PersistedEventOutput {
  transactionId: string
  globalSequence: number
  streamVersion: number
  eventId: string
  streamId: string
  eventType: string
  occurredAtMs: number
  payload: Buffer
}
/** A handle to one control-plane store (`ControlPlaneStore`). */
export declare class Store {
  /**
   * Open (or create) a store at `path`. `durability` is "strict" (default)
   * or "relaxed".
   */
  static open(path: string, durability?: string | undefined | null): Store
  /** Drop the underlying store and its connections. Further calls throw. */
  close(): void
  /** Atomically commit events, projection patches, and job operations. */
  commit(batch: CommitBatchInput): CommitReceiptOutput
  /** Claim ready jobs from one queue. */
  claimJobs(request: ClaimRequestInput): ClaimOutcomeOutput
  /** Durably extend an active lease. */
  extendLease(jobId: string, leaseToken: string, newExpiryMs: number, nowMs: number): LeaseExtensionReceiptOutput
  /** Recover an indeterminate claim, reconstructing original lease tokens. */
  recoverClaim(transactionId: string, nowMs: number): ClaimOutcomeOutput
  /** Recover the outcome of an indeterminate commit. */
  recoverTransaction(transactionId: string): TransactionRecoveryOutput
  /** List jobs, optionally filtered by queue and state, in enqueue order. */
  jobs(queue: string | undefined | null, state: string | undefined | null, limit: number): Array<JobInfoOutput>
  /** Look up one job by its ID. */
  job(jobId: string): JobInfoOutput | null
  /**
   * List one page of jobs after a pagination cursor (an enqueue-sequence
   * value; start from 0), optionally filtered by queue and state. Returns
   * the page and the cursor to pass for the next page.
   */
  jobsPage(queue: string | undefined | null, state: string | undefined | null, afterSequence: number, limit: number): JobsPageOutput
  /** Get one projection entry by key. */
  projectionGet(projection: string, key: Buffer): Buffer | null
  /** The current version of a projection (0 when it does not exist). */
  projectionVersion(projection: string): number
  /** The current durable version of a stream (0 when it does not exist). */
  streamVersion(streamId: string): number
  /** Events with a global sequence strictly greater than `after`, oldest first. */
  eventsAfter(after: number, limit: number): Array<PersistedEventOutput>
}
